insert into clients (name) values
    ('Lumon Industries'),
    ('Dunder Mifflin'),
    ('Vandelay Industries'),
    ('Sterling Cooper'),
    ('Pied Piper'),
    ('Waystar Royco'),
    ('Los Pollos Hermanos'),
    ('Massive Dynamic'),
    ('Bluth Company'),
    ('Wernham Hogg'),
    ('Oceanic Airlines'),
    ('Buy More'),
    ('Prestige Worldwide'),
    ('Chartwell Pharmaceuticals'),
    ('Strickland Propane'),
    ('Rekall Inc.'),
    ('E Corp (Evil Corp)'),
    ('Globex Corporation'),
    ('GNB (Goliath National Bank)'),
    ('GreenTech');