# DEFAULTS
ARG SUPABASE_TAG=36efe0f

# Use Supabase as BASE
FROM ghcr.io/train360-corp/supabase:${SUPABASE_TAG} AS supabase

# directly build with migrations
COPY ./supabase/migrations /supabase/migrations
ENV AUTO_MIGRATIONS_MODE=mounted

# Auth
ENV GOTRUE_JWT_EXP=604800
ENV GOTRUE_URI_ALLOW_LIST=""
ENV GOTRUE_DISABLE_SIGNUP="false"
ENV GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED="false"

# Email
ENV GOTRUE_EXTERNAL_EMAIL_ENABLED="true"
ENV GOTRUE_MAILER_AUTOCONFIRM="false"
ENV GOTRUE_SMTP_ADMIN_EMAIL=""
ENV GOTRUE_SMTP_HOST=""
ENV GOTRUE_SMTP_PORT=587
ENV GOTRUE_SMTP_USER=""
ENV GOTRUE_SMTP_PASS=""
ENV GOTRUE_SMTP_SENDER_NAME="ProjDocs"

# Storage
ENV UPLOAD_FILE_SIZE_LIMIT=52428800
ENV UPLOAD_SIGNED_URL_EXPIRATION_TIME=120

# Expose Auth/Kong Port
EXPOSE 8000