version: "3.8"

services:
  supabase:
    image: ghcr.io/train360-corp/supabase:latest
    container_name: supabase
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
      - "8000:8000"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./storage_data:/supabase/storage/data