alter table "public"."files" add column "number" bigint generated by default as identity not null;

CREATE UNIQUE INDEX files_number_key ON public.files USING btree (number);

alter table "public"."files" add constraint "files_number_key" UNIQUE using index "files_number_key";


