name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'build-web.yml'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # required for GitHub OIDC token authentication

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm i

      - run: npm run build
        working-directory: ./apps/web